[package]
name = "orienteering"
version = "0.1.0"
edition = "2024"

[features]
default = ["serde"]
serde = ["dep:serde", "nalgebra/serde-serialize"]

[dependencies]
derive_more = { version = "2.0.1", features = [
  "add",
  "as_ref",
  "deref",
  "deref_mut",
  "from",
  "mul",
] }
nalgebra = "0.33.2"
rand = { version = "0.9.1", features = ["small_rng", "std_rng"] }
serde = { version = "1.0.219", features = ["derive"], optional = true }

[dev-dependencies]
bevy = "0.16.0"
