[workspace]
members = [
  "crates/orienteering_bevy",
]

[package]
name = "orienteering"
version = "0.1.0"
edition = "2024"

[features]
default = ["serde"]
serde = ["dep:serde", "nalgebra/serde-serialize"]

[dependencies]
derive_more = { version = "2.0.1", features = [
  "add",
  "as_ref",
  "deref",
  "deref_mut",
  "from",
  "mul",
] }
enum_dispatch = "0.3.13"
nalgebra = "0.33.2"
ordered-float = { version = "5.0.0", features = ["serde"] }
rand = { version = "0.9.1", features = ["small_rng", "std_rng"] }
serde = { version = "1.0.219", features = ["derive"], optional = true }
strum = { version = "0.27.1", features = ["derive"] }

[dev-dependencies]
