[package]
name = "orienteering_bevy"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "scalar-field"
path = "src/bin/scalar_field.rs"

[[bin]]
name = "demo"
path = "src/bin/main.rs"


[dependencies]
bevy = { version = "0.16.0", features = ["dynamic_linking"] }
log = "0.4.27"
nalgebra = "0.33.2"

orienteering = { path = "../../" }
